config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :letters  
  resources :notices
  resources :guests do
  	resources :letters
  end

  get 'home/index'

  get 'welcome/index'

  get 'signup'    => 'guests#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
	has_many :letters
	validates :name,		presence: true,		length:{minimum: 1,  maximum: 48}
	has_secure_password
	validates :password,	presence: true,		length:{minimum: 1,  maximum: 48}
end

app/models/letter.rb
class Letter < ApplicationRecord
	validates :sender,		presence: true,		length:{minimum: 1,  maximum: 48}
	validates :receiver,	presence: true,		length:{minimum: 1,  maximum: 48}
	# validates :content,	presence: true,		length:{maximum: 1024}
	# validates :state,		presence: true
	# validates :authority,	presence: true
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  	 def logged_in_guest
      get_guest_letters_send
      get_geust_letters_receive
      unless logged_in? 
        store_location
        flash[:danger] = "Please log in." 
        redirect_to login_path 
      end
    end

    def correct_guest
       @guest = Guest.find(session[:guest_id]) 
       redirect_to(guests_path) unless current_guest?(@guest)
    end

    def get_guest_letters
      @guest_letters = Letter.where("sender = ? OR receiver = ?", session[:guest_id], session[:guest_id])
    end

    def get_geust_letters_receive
      @guest_letters_receive = Letter.where(receiver: session[:guest_id])
    end

    def get_guest_letters_send
      @guest_letters_send = Letter.where(sender: session[:guest_id])
    end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :logged_in_guest, only: [:edit, :show, :update]
  before_action :correct_guest,   only: [:edit, :show, :update]  
  before_action :store_keeper, only: [:index ,:destroy]
  def index
    @guests = Guest.all
  end

  def new
  	@guest = Guest.new
  end

  def show
    @guest = Guest.find(params[:id])
    # get_guest_letters
    # get_guest_letters_send
    # get_geust_letters_receive
    
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      flash[:success] = "Welcome to the he TMiracle of the Grocery !"
      redirect_back_or @guest
    else
      render 'new'
    end
  end

  def update
    @guest = Guest.find(params[:id])

    if @guest.update(guest_params)
      redirect_to @guest
    else
      render 'edit'
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
 
    redirect_to guests_path
  end

  private
    def guest_params
      params.require(:guest).permit(:name, :password)
    end

    def store_keeper
      redirect_to(guests_path) unless current_guest.storekeeper?    
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  # skip_before_filter :verify_authenticity_token
  before_action :logged_in_guest, only: [:new, :edit, :show, :update]
  before_action :correct_guest,   only: [:new, :edit, :show, :update]

  def index
    @letters = Letter.paginate(:page => params[:page],:per_page => 2)
  end

  def new
  	@letter = Letter.new
  end

  def show
    @letter = Letter.find(params[:id])
    @letter.sender = getGuestNameById(params[:id])
    @letter.receiver = getGuestNameById(params[:id])
  end

  def edit
    @letter = Letter.find(params[:id])
  end

  def create
    receiver = Guest.where("name = ? ", params[:letter][:receiver]).first
    @letter = Letter.new(letter_params)
    @letter.receiver = receiver[:id]
    @letter.sender = session[:guest_id]

    if @letter.save
      flash[:success] = "letter has been sended!"
      render plain: "发送成功，请关闭编辑窗口。"
    else
      render 'new'
    end
  end

  def update
    @letter = Letter.find(params[:id])

    if @letter.update(letter_params)
      redirect_to @letter
    else
      render 'edit'
    end
  end

  def destroy
    @letter = Letter.find(params[:id])
    @letter.destroy
 
    redirect_to letters_path
  end

  private
    def letter_params
      params.require(:letter).permit(:sender, :content, :receiver, :created_at)
    end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
	def index
    @notices = Notice.all
  end

  def new
  	@notice = Notice.new
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def create
    @notice = Notice.new(notice_params)
    if @notice.save
      redirect_to @notice
    else
      render 'new'
    end
  end

  def update
    @notice = Notice.find(params[:id])

    if @notice.update(notice_params)
      redirect_to @notice
    else
      render 'edit'
    end
  end

  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy
 
    redirect_to notices_path
  end

  private
    def notice_params
      params.require(:notice).permit(:title, :content, :publisher, :created_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	guest = Guest.find_by(name: params[:session][:name].downcase) 
  	if guest && guest.authenticate(params[:session][:password])
      log_in guest
  		redirect_back_or guest
  	else
  		flash[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out redirect_to login_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(guest)
 		session[:guest_id] = guest.id  
 	end

 	def log_out(guest)
 		session.delete(:guest_id) 
 		@current_guest = nil  
 	end

 	def logged_in?
 		!current_guest.nil?
	end

	def current_guest
      	@current_guest ||= Guest.find_by(id: session[:guest_id])  
    end

    def current_guest?(guest)
 		@guest == current_guest  
 	end

 	# 重定向到存储的地址，或者默认地址
  	def redirect_back_or(default)
 		redirect_to(session[:forwarding_url] || default) 
 		session.delete(:forwarding_url)  
 	end

  	# 存储以后需要获取的地址
  	def store_location
 		session[:forwarding_url] = request.url if request.get?  
 	end

 	def getGuestNameById(id)
      guest = Guest.find_by id: id
	guest[:name]

    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/guests/_form.html.erb
<%= form_for @guest do |f| %>
	<% if @guest.errors.any? %>
  	<div id="error_explanation">
    	<h2><%= pluralize(@guest.errors.count, "error") %> 
    	prohibited this letter from being saved:</h2>
    	<ul>
    	<% @guest.errors.full_messages.each do |msg| %>
      		<li><%= msg %></li>
    	<% end %>
    	</ul>
  	</div>
  	<% end %>

  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %>
  </div>
  <% end %>

  <div id="form_guest" class="col-lg-4" style="border: solid 1px;">
    <div id="name" class="input-group">
      <span class="input-group-addon"><i class="fa fa-1x fa-user" aria-hidden="true"></i></span>
      <%= f.text_field :name, class:"form-control", placeholder:"昵称"%>
    </div>
    <div id="password" class="input-group" style="margin-top: 10px; margin-bottom: 10px;">
      <span class="input-group-addon"><i class="fa fa-1x fa-lock" aria-hidden="true"></i></span>
      <%= f.password_field :password, class:"form-control", placeholder:"密码"%>
    </div>
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "guests.css" %>
<div id="guest" class="container col-lg-offset-2 col-lg-8" style="background-color: #FFF;">
	<%= render 'form' %>
</div>
<% if current_guest.storekeeper? || curect_guest?(@guest) %>
 | <%= link_to "delete", @guest, method: :delete,
 data: { confirm: "You sure?" } %>
 <% else %>
 <strong>无权修改</strong>
 <% end %>

app/views/guests/index.html.erb
<h1>Listing guests</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @guests.each do |guest| %>
    <tr>
      <td><%= guest.id %></td>
      <td><%= guest.name %></td>
      <td><strong><%= guest.password %></strong></td>
      <td><%= guest.password_digest %></td>
      <td><%= link_to 'Show', guest_path(guest) %></td>
      <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
      <td><%= link_to 'Del',  guest_path(guest),
              method: :delete,
              data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'New letter', new_guest_path %>

app/views/guests/new.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "guests.css" %>
<div id="" class="container col-lg-12">
	<div id="header">
		<%= render 'layouts/header' %>
	</div>
	<br>
	<div id="guest" class="col-lg-offset-4 col-lg-8" style="background-color: #FFF;">
		<div class="card">
  			<div class="card-block">
    			<h4 class="card-title">用户注册</h4>
    			<h6 class="card-subtitle text-muted">解忧杂货店</h6>
  			</div>
  			<div class="card-block">
				<%= render 'form' %>
  			</div>
		</div>
	</div>		
</div>

app/views/guests/show.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "guests.css" %>

<div id="" class="container col-lg-12">
	<div id="header" style="margin-bottom: 40px;">
		<%= render 'layouts/header' %>
	</div>
	<br>
	<div class="col-lg-2">
		<%= render 'letters/mailbox' %>
	</div>
	<div class="col-lg-10">
		<%= render 'letters/maillist' %>
	</div>
	
	<%= link_to 'Back', guests_path %>
| <%= link_to 'Edit', edit_guest_path(@guest) %>	
</div>

app/views/home/index.html.erb
<div id="home" class="container col-lg-12">
	<div id="header">
		<%= render 'layouts/header' %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color: #F1F1F1; border: none;">
<a class="navbar-brand col-lg-2" href="/">
<span><img src="../../images/logo.ico" style="width: 48px;"></span>&nbsp;&nbsp;解忧杂货店</a>
<% if logged_in? %>
  	<form class="form-inline navbar-form pull-left">
    	<input class="form-control " type="text" placeholder="Search">
    	<button class="btn btn-success-outline" type="submit">Search</button>
  	</form>
<% end %>
<div class="container">
 	<nav>
 		<ul class="nav navbar-nav navbar-right">
 			<% if logged_in? %>
 			<li class="nav-item dropdown">
 				<a href="#" class=" dropdown-toggle" data-toggle="dropdown"   aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i>
 				<%= current_guest.name %> 
 				<b class="caret"></b>
 				</a>
 				<ul class="dropdown-menu">
 					<li><%= link_to "个人", current_guest %></li>
 					<li><%= link_to "设置", '#' %></li>
 					<li class="divider"></li>
 					<li>
  						<%= link_to "退出", logout_path, method: "delete" %>
 					</li>
 				</ul>
 			</li>
  			<% else %>
  			<li><%= link_to "Log in", login_path %></li>
  			<% end %>
 		</ul>
 	</nav>
</div>
</header>
<script src="//cdn.bootcss.com/tether/1.4.0/js/tether.min.js"></script>
<script type="text/javascript" src="//cdn.bootcss.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Miracle of the Grocery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/letters/_form.html.erb
<%= form_for @letter do |f| %>
	<% if @letter.errors.any? %>
  	<div id="error_explanation">
    	<h2><%= pluralize(@letter.errors.count, "error") %> 
    	prohibited this letter from being saved:</h2>
    	<ul>
    	<% @letter.errors.full_messages.each do |msg| %>
      		<li><%= msg %></li>
    	<% end %>
    	</ul>
  	</div>
  	<% end %>

  	<% flash.each do |message_type, message| %>
  	<div class="alert alert-<%= message_type %>"><%= message %>
  	</div>
  	<% end %>

  	<div class="col-lg-12" style=" background-color: #404040; height:25px;   color:#FFF;">
  		写信
  	</div>
	<div class="col-lg-12" id="receiver">
		<!-- <i class="fa fa-2x fa-user" aria-hidden="true" style="color: #00ADF8; font-weight: bold;">&nbsp;&nbsp;</i> -->
		<%= f.text_field :receiver, class:"stationery", placeholder:"收信人" %>
	</div>
	<div id="content" style="margin-top: 10px;">
		<%= f.text_area :content, style:"width:100%; height: 460px; text-indent:2em; overflow-y:scroll; scrollbar-base-color: #2AAA96", class:"stationery", placeholder:"正文" %>
	</div>
	<div id="inscribe" style="float: right;">
		<!-- <div id="sender">
			<i class="fa fa-2x fa-user" aria-hidden="true" style="color: #00ADF8; font-weight: bold;">&nbsp;&nbsp;</i>
			<%= f.text_field :sender, class:"stationery", placeholder:" 署名" %>
		</div>
		<div id="senderdate">
			<i class="fa fa-2x fa-calendar" aria-hidden="true" style="color: #00ADF8; font-weight: bold;">&nbsp;&nbsp;</i>
			<%= f.text_field :created_at, class:"stationery", placeholder:"日期" %>
		</div> -->

		<div id="action" style="margin-top: 5px; margin-left: 20px;">
			<button type="button" class="btn btn-link">保存草稿</button>
			<i class="fa fa-1x fa-paper-plane" aria-hidden="true"></i>
			<%= f.submit class:"btn btn-primary", style:"background-color:#10C8DD; margin-left:5px; border: none; font-size: 16px;" %>
		</div>
	</div>
	<!-- <div id="back" style="margin-top: 80px;">
		<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
		<%= link_to 'Back', letters_path %>
	</div> -->
	
<% end %>

app/views/letters/_mailbox.html.erb
<div id="mailbox">
	<div class="col-lg-12">
		<button type="button" class="btn btn-primary  col-lg-10" data-toggle="modal" data-target="#myModal" style="background-color:#D84A38; border: none;">写信</button>
		
	<!-- Modal -->
		<div class="modal col-lg-offset-3 col-lg-8" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:#FFF;">
          			<span aria-hidden="true">&times;</span>
          			<span class="sr-only">Close</span>
        		</button>
        	</div>
			<iframe src="/letters/new" style="width: 100%; height: 90%;"></iframe>
		</div>
	</div>
	<div class="list-group col-lg-offset-1 col-lg-9" style="margin-top: 10px;">
		<ul class="nav nav-tabs" role="tablist">
			<li class="nav-item active">
    			<a class="nav-link" href="#receive" role="tab" data-toggle="tab">收信箱&nbsp;&nbsp;(<%= @guest_letters_receive.count %>)</i></a>
  			</li>
  			<li class="nav-item">
    			<a class="nav-link active" href="#send" role="tab" data-toggle="tab">寄信箱&nbsp;&nbsp;(<%= @guest_letters_send.count %>)</a>
  			</li>
  			<li class="nav-item">
    			<a class="nav-link" href="#messages" role="tab" data-toggle="tab"><i class="fa fa-history" aria-hidden="true">草稿</i></a>
  			</li>
		</ul>
	</div>
	
	
	
</div>

app/views/letters/_maillist.html.erb
<div id="maillist">
	<div class="col-lg-3" style="margin-bottom: 5px;">
		<div class="btn-group">
  			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-square-o" aria-hidden="true"></i>&nbsp;&nbsp;<i class="fa fa-caret-down" aria-hidden="true"></i>
  			</button>
 			<ul class="dropdown-menu">
 				<li><a class="dropdown-item" href="#"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;全部</a></li>
    			<li><a class="dropdown-item" href="#"><i class="fa fa-envelope-open" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;已读</a></li>
    			<li><a class="dropdown-item" href="#"><i class="fa fa-envelope-open-o" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;未读</a></li>
 			</ul>
		</div>
		<button type="button" class="btn btn-default">&nbsp;&nbsp;<i class="fa fa-refresh" aria-hidden="true">&nbsp;&nbsp;</i>
		</button>
	</div>
	<div class="col-lg-offset-5 col-lg-4" style="font-size: 120%;">
		第1-50封，共100封
		<button type="button" class="btn btn-secondary btn-sm"><i class="fa fa-chevron-left" aria-hidden="true"></i></button>
		<button type="button" class="btn btn-secondary btn-sm"><i class="fa fa-chevron-right" aria-hidden="true"></i></button>
		<button type="button" class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog" aria-hidden="true"></i>&nbsp;&nbsp;<i class="fa fa-caret-down" aria-hidden="true"></i></button>
		<ul class="dropdown-menu pull-right">
 			<li><a class="dropdown-item" href="#"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;标准</a></li>
    		<li><a class="dropdown-item" href="#"><i class="fa fa-envelope-open" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;适中</a></li>
    		<li><a class="dropdown-item" href="#"><i class="fa fa-envelope-open-o" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;&nbsp;紧凑</a></li>
 		</ul>
	</div>
	<div class="col-lg-12">
		<ul class="nav nav-tabs" role="tablist">
			<li class="nav-item active">
    			<a class="nav-link" href="#receive" role="tab" data-toggle="tab"><i class="fa fa-paper-plane" aria-hidden="true">收信箱</i></a>
  			</li>

  			<li class="nav-item">
    			<a class="nav-link" href="#send" role="tab" data-toggle="tab"><i class="fa fa-paper-plane-o" aria-hidden="true"></i>寄信箱</a>
  			</li>
  			
  			<li class="nav-item">
    			<a class="nav-link" href="#messages" role="tab" data-toggle="tab"><i class="fa fa-history" aria-hidden="true">草稿</i></a>
  			</li>
		</ul>

		<!-- Tab panes -->
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="receive">
  				<ul class="list-group">
					<% @guest_letters_receive.each do |letter| %>
  					<li class="list-group-item" style="height:40px;">
  						<span class="col-lg-2 label label-default label-pill pull-right"><%= letter.created_at %></span>
  						<div class="col-lg-1"><i class="fa fa-square-o" aria-hidden="true"></i></div>
  						<div class="col-lg-2"><%= getGuestNameById(letter.sender) %></div>
  						<div class="col-lg-7"><%= link_to letter.content.slice(0, 20), letter_path(letter) %></div>
  				
    				</li>
  					<% end %>
				</ul>
  			</div>

  			<div role="tabpanel" class="tab-pane" id="send">
  				<ul class="list-group">
					<% @guest_letters_send.each do |letter| %>
  					<li class="list-group-item" style="height:40px;">
  						<span class="col-lg-2 label label-default label-pill pull-right"><%= letter.created_at %></span>
  						<div class="col-lg-1"><i class="fa fa-square-o" aria-hidden="true"></i></div>
  						<div class="col-lg-2"><%= getGuestNameById(letter.receiver) %></div>
  						<div class="col-lg-7"><%= link_to letter.content.slice(0, 20), letter_path(letter) %></div>
  				
    				</li>
  					<% end %>
				  </ul>
  			</div>

  			<div role="tabpanel" class="tab-pane" id="messages">草稿</div>
		</div>
		
	</div>
  
</div>

app/views/letters/create.html.erb
<h1>Letters#create</h1>
<p>Find me in app/views/letters/create.html.erb</p>

app/views/letters/edit.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "letters.css" %>
<div id="letter" class="container col-lg-offset-2 col-lg-8" style="background-color: #FFF;">
	<div id="top" style="height: 80px;">
		<div id="header" style="height: 20px; background-color: #FF005B">
			<div id="horizontal" class="col-lg-offset-1" style="color: #00ADF8">
			</div>
			
			<div id="vertical" class="col-lg-offset-1" style="width: 10px; height: 80px; background-color:#00ADF8; float: left">	
			</div>
			
			<div id="mark" class="col-lg-offset-1" style="padding-top:40px; padding-left: 20px; font-size: 200%; color: #00ADF8">
				解忧杂货店
			</div>
		</div>
	</div>

	<div id="middle" class="col-lg-offset-1" style="height: 550px; margin-top: 30px;">
		<%= render 'form' %>
	</div>

	<div id="bottom" style="height: 30px; background-color: #00ADF8">
		
	</div>
</div>

app/views/letters/index.html.erb
<h1>Listing leeters</h1>
<%= will_paginate @letters,renderer: BootstrapPagination::Rails %>
<table>
  <tr>
    <th>Sender</th>
    <th>Receiver</th>
    <th>Content</th>
  </tr>
  <ul>
  <% @letters.each do |letter| %>
    <tr>
      <td><%= letter.sender %></td>
      <td><%= letter.receiver %></td>
      <td><%= letter.content %></td>
      <td><%= link_to 'Show', letter_path(letter) %></td>
      <td><%= link_to 'Edit', edit_letter_path(letter) %></td>
      <td><%= link_to 'Del',  letter_path(letter),
              method: :delete,
              data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'New letter', new_letter_path %>

app/views/letters/new.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "letters.css" %>
<div id="" class="container col-lg-12">
	<div class="col-lg-10">
		<%= render 'form' %>
	</div>
	
</div>

app/views/letters/show.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "letters.css" %>
<div id="letter" class="container col-lg-offset-2 col-lg-8" style="background-color: #FFF;">
	<div id="top" style="height: 80px;">
		<div id="header" style="height: 20px; background-color: #FF005B">
			<div id="horizontal" class="col-lg-offset-1" style="color: #00ADF8">
			</div>
			
			<div id="vertical" class="col-lg-offset-1" style="width: 10px; height: 80px; background-color:#00ADF8; float: left">	
			</div>
			
			<div id="mark" class="col-lg-offset-1" style="padding-top:40px; padding-left: 20px; font-size: 200%; color: #00ADF8">
				解忧杂货店
			</div>
		</div>
	</div>

	<div id="middle" class="col-lg-offset-1" style="height: 550px; margin-top: 30px;">
		<%= render 'form' %>
		<%= link_to 'Back', letters_path %>
	</div>

	<div id="bottom" style="height: 30px; background-color: #00ADF8">
		
	</div>
</div>

<%= link_to 'Back', letters_path %>
| <%= link_to 'Edit', edit_letter_path(@letter) %>

app/views/notices/edit.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "notices.css" %>
<div id="notice" class="container col-lg-offset-2 col-lg-8" style="background-color: #FFF;">
	<div id="top" class="col-lg-12">
		<img src="/images/notice/lamp.jpg" >
				
	</div>

	<div id="middle" class="col-lg-offset-1 col-lg-10" style="height: 500px; border: solid 5px; border-color: #232321">
		<%= render 'form' %>
	</div>

	<div id="bottom" class="col-lg-12" style="height: 30px; background-color: #FFF">
		
	</div>
</div>

app/views/notices/index.html.erb
<h1>Listing notices</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @notices.each do |notice| %>
    <tr>
      <td><%= notice.title %></td>
      <td><%= notice.content %></td>
      <td><%= link_to 'Show', notice_path(notice) %></td>
      <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
      <td><%= link_to 'Del',  notice_path(notice),
              method: :delete,
              data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'New notice', new_notice_path %>

app/views/notices/new.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "notices.css" %>
<div id="notice" class="container col-lg-offset-2 col-lg-8" style="background-color: #FFF;">
	<div id="top" class="col-lg-12">
		<img src="/images/notice/lamp.jpg" >
				
	</div>

	<div id="middle" class="col-lg-offset-1 col-lg-10" style="height: 500px; border: solid 5px; border-color: #232321">
		<%= render 'form' %>
	</div>

	<div id="bottom" class="col-lg-12" style="height: 30px; background-color: #FFF">
		
	</div>
</div>

app/views/notices/show.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "notices.css" %>
<div id="notice" class="container col-lg-offset-2 col-lg-8" style="background-color: #FFF;">
	<div id="top" class="col-lg-12">
		<img src="/images/notice/lamp.jpg" >
				
	</div>

	<div id="middle" class="col-lg-offset-1 col-lg-10" style="height: 500px; border: solid 5px; border-color: #232321">
		<%= render 'form' %>
	</div>

	<div id="bottom" class="col-lg-12" style="height: 30px; background-color: #FFF">
		
	</div>
</div>